### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by anton-piliugin** [vitalets/websocket-as-promised#18]
In IE11 doesn't work without https://cdnjs.com/libraries/babel-polyfill

**Comment by vitalets** [comment]
Could you show errors from console?
Maybe it's reasonable to include polyfill for missing things, not whole babel-polyfill.

**Comment by anton-piliugin** [comment]
> Could you show errors from console?
> Maybe it's reasonable to include polyfill for missing things, not whole babel-polyfill.

"SCRIPT5022: **Исключение брошено и не поймано**", link: https://docs.microsoft.com/ru-ru/previous-versions/w4e7h3yz(v=vs.94)
Here: `...if("function"!=typeof Promise)throw new TypeError("`Promise.prototype.finally` requires a global `Promise` be available.");`
