### ISSUE TITLE
Self-signed certs

### ISSUE THREAD

**Issue by narsariusv** [vitalets/websocket-as-promised#19]
Getting connection errors due to self-signed certs. Is their an option similar to ws that allows you to bypass the connection error?

```
const WebSocket = require('ws');
const ws = new WebSocket('wss://url',{rejectUnauthorized: false});
```

**Comment by narsariusv** [comment]
Resolved - Had to use ws instead of websockets. Then as ws wouldn't work I had to implement the fix from https://github.com/vitalets/websocket-as-promised/issues/15#issuecomment-444023014

**Comment by vitalets** [comment]
@narsariusv 
Does the connection closed only when used with websocket-as-promised?

**Comment by vitalets** [comment]
Working with `ws` package is now officially supported (since 0.10.0).
Please have a look on [this section](https://github.com/vitalets/websocket-as-promised#usage-with-ws) in readme.
