### ISSUE TITLE
[Question] As a server usage or how to pass PORT to listen to?

### ISSUE THREAD

**Issue by ArturJS** [vitalets/websocket-as-promised#25]
Hello @vitalets,

Just out of curiosity, is it possible to use `websocket-as-promised` as a websocket server akin to `ws` module?

For example:
https://github.com/websockets/ws#simple-server
```js
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });
  ws.send('something');
});
```

If it's not can I submit PR that will introduce this functionality?
Thanks!

**Comment by vitalets** [comment]
hi @ArturJS 
`websocket-as-promised` is intended to be a client, not server. Because in case of server, it's not clear what should be promisified. Your example with `ws` looks nice to me.  
You can use any websocket server library for `websocket-as-promised` client.

**Comment by ArturJS** [comment]
@vitalets hmm, interesting...
Thanks for the information!
Just didn't know that it's a client only library.
Closing as resolved.
