### ISSUE TITLE
Is there a good way to use this in vanilla JS?

### ISSUE THREAD

**Issue by adroslice** [vitalets/websocket-as-promised#27]
We run a Go backend with an HTML+JS+JQuery frontend. Currently we're using reconnecting-websocket for communication, but having request and response in different functions complicates things greatly, so we were looking for a library that wraps it in a way so we can use async/await. I have no idea how Node.js works, and I'm 99.9% sure that we don't want to depend on it.

**Comment by vitalets** [comment]
Hey! This is client library, so you can use it with any backend (including go for sure).
Please note that auto-reconnecting is not in scope of this library and should be added by end app (see #6)
