### ISSUE TITLE
Formal LICENSE file

### ISSUE THREAD

**Issue by cameronelliott** [vitalets/websocket-as-promised#33]
@vitalets Hey Vitaliy, this is an awesome looking library! 
But I almost decided not to use it, because I did not see a license file.
After searching around I did see the MIT letters next to your name, but
I know if I show this to any company's legal team, they will most likely
say, "that's not sufficient evidence of a MIT license".

Would you accept a PR with the MIT license with your name on it, or 
please consider adding one?
Some users may not find a LICENSE and avoid this package,
which is a shame, because it looks awesome to me.

Thanks,
Cameron

**Comment by vitalets** [comment]
Hi @cameronelliott !
Thanks for pointing on that!
[License file](https://github.com/vitalets/websocket-as-promised/blob/master/LICENSE) added.
