### ISSUE TITLE
failed to get response from server

### ISSUE THREAD

**Issue by XDinEuro** [vitalets/websocket-as-promised#45]
Hi, I am using sendRequest() API, and always failed to get response even though I send it from server with same request id.

Here is the detailed code.
```
const ws = new WebSocketAsPromised('ws://127.0.0.1:8000/ws', {
          packMessage: data => JSON.stringify(data),
          unpackMessage: data => JSON.parse(data),
         attachRequestId: (data, requestId) => Object.assign({id: requestId}, data), // attach requestId to message as `id` field
         extractRequestId: data => data && data.id, 
      });
ws.onMessage.addListener(message => console.log("received ", message));
ws.open();

// send request 
await ws.sendRequest({ task: 'move_ptp' }, { requestId: 1 })
.then((response) => { console.log("responsed"); console.log(response) });

console.log("finished");
```

I have a server running behind, sending response with same message after 1 second receiving request. 

When I run the code I only see the log in `onMessage`, but not in promise, and I didn't see "finished".

I wonder, did I configure something wrong ? Or I didn't extract requestID from received message correctly ?

**Comment by XDinEuro** [comment]
@vitalets

**Comment by XDinEuro** [comment]
By the way, if I use 
ws.sendPacked({ task: 'move_ptp' });
const response = await this.ws?.waitUnpackedMessage(data => data && data.task === 'move_ptp')
console.log("response is ", response)

it works fine.

**Comment by vitalets** [comment]
Hi @XDinEuro 
Could you show logs from client and server side to be sure that all required messages sent?

**Comment by XDinEuro** [comment]
Hi, thanks for the reply.

I just changed the code to

```
// send request 
await ws.open().then(() => {ws.sendRequest({ task: 'move_ptp' }, { requestId: 1 })})
.then((response) => { console.log("responsed"); console.log(response) });
```

Then it works.

I think the reason is I shouldn't mix synchronous call and asynchronous call together.

**Comment by vitalets** [comment]
Yeap!
You could also replace all `then` with `await`:
```js
// send request 
await ws.open();
const response = await ws.sendRequest({ task: 'move_ptp' }, { requestId: 1 });
console.log("responsed"); 
console.log(response);
```
