### ISSUE TITLE
Feature request: Add support for lazy `send` (e.g. trigger `open` if `!isOpened`)

### ISSUE THREAD

**Issue by titanism** [vitalets/websocket-as-promised#46]
Right now the logic is to throw an error if the connection is not already opened when `send` is called (either directly or via `sendPacked`, `sendRequest`, etc).

<https://github.com/vitalets/websocket-as-promised/blob/bc60644c935b69eba1284f5863d3d91099165bd0/src/index.js#L251-L255C4>

It would be great to alter this behavior to support a `lazy` option (Boolean, and `false` by default).  If `true`, then it would attempt to open the connection inside of `send()` function.

**Comment by vitalets** [comment]
From the lib perspective I suggest to keep such wrapper in userland.
As `wsp.open()` handles this correctly, the wrapper is rather simple:
```js
async lazySend(data) {
  await wsp.open();
  await wsp.send(data);
}
```
But you can setup your own handling of broken connections, retries, etc.
